export FZF_DEFAULT_COMMAND="rg --files --hidden"
export EDITOR=nvim
export VISUAL=nvim
export TERMINAL=alacritty
export TERM=alacritty
export BROWSER=firefox
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.config/zsh/custom
export PATH=$HOME/.yarn/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH
